//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 02:25:39 PM MSK 
//


package ru.yandex.qatools.camelot.core.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for FailConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FailConfig">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:beans.qa.yandex.ru}BaseConfig">
 *       &lt;sequence>
 *         &lt;element name="numFailures" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FailConfig", propOrder = {
    "numFailures"
})
public class FailConfig
    extends BaseConfig
    implements Serializable
{

    @XmlElement(defaultValue = "3")
    protected int numFailures;

    /**
     * Gets the value of the numFailures property.
     * 
     */
    public int getNumFailures() {
        return numFailures;
    }

    /**
     * Sets the value of the numFailures property.
     * 
     */
    public void setNumFailures(int value) {
        this.numFailures = value;
    }

}
