//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 02:25:39 PM MSK 
//


package ru.yandex.qatools.camelot.core.beans;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Notification.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Notification">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TestPassed"/>
 *     &lt;enumeration value="TestFailed"/>
 *     &lt;enumeration value="TestBroken"/>
 *     &lt;enumeration value="TestSkipped"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Notification")
@XmlEnum
public enum Notification {

    @XmlEnumValue("TestPassed")
    TEST_PASSED("TestPassed"),
    @XmlEnumValue("TestFailed")
    TEST_FAILED("TestFailed"),
    @XmlEnumValue("TestBroken")
    TEST_BROKEN("TestBroken"),
    @XmlEnumValue("TestSkipped")
    TEST_SKIPPED("TestSkipped");
    private final String value;

    Notification(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Notification fromValue(String v) {
        for (Notification c: Notification.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
