//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 02:25:39 PM MSK 
//


package ru.yandex.qatools.camelot.core.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.yandex.qa.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.yandex.qa.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestSkipped }
     * 
     */
    public TestSkipped createTestSkipped() {
        return new TestSkipped();
    }

    /**
     * Create an instance of {@link Config }
     *
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Meta }
     *
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Failure }
     *
     */
    public Failure createFailure() {
        return new Failure();
    }

    /**
     * Create an instance of {@link Event }
     *
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link TestFailed }
     *
     */
    public TestFailed createTestFailed() {
        return new TestFailed();
    }

    /**
     * Create an instance of {@link TestBroken }
     *
     */
    public TestBroken createTestBroken() {
        return new TestBroken();
    }

    /**
     * Create an instance of {@link TestPassed }
     *
     */
    public TestPassed createTestPassed() {
        return new TestPassed();
    }

    /**
     * Create an instance of {@link TestStarted }
     *
     */
    public TestStarted createTestStarted() {
        return new TestStarted();
    }

    /**
     * Create an instance of {@link GolemSubscriber }
     *
     */
    public GolemSubscriber createGolemSubscriber() {
        return new GolemSubscriber();
    }

    /**
     * Create an instance of {@link WebhookSubscriber }
     *
     */
    public WebhookSubscriber createWebhookSubscriber() {
        return new WebhookSubscriber();
    }

    /**
     * Create an instance of {@link EmailSubscriber }
     *
     */
    public EmailSubscriber createEmailSubscriber() {
        return new EmailSubscriber();
    }

    /**
     * Create an instance of {@link SmsConfig }
     *
     */
    public SmsConfig createSmsConfig() {
        return new SmsConfig();
    }

    /**
     * Create an instance of {@link TestDropped }
     *
     */
    public TestDropped createTestDropped() {
        return new TestDropped();
    }

    /**
     * Create an instance of {@link FailConfig }
     *
     */
    public FailConfig createFailConfig() {
        return new FailConfig();
    }

    /**
     * Create an instance of {@link WebhookConfig }
     *
     */
    public WebhookConfig createWebhookConfig() {
        return new WebhookConfig();
    }

    /**
     * Create an instance of {@link SmsSubscriber }
     *
     */
    public SmsSubscriber createSmsSubscriber() {
        return new SmsSubscriber();
    }

    /**
     * Create an instance of {@link EmailConfig }
     *
     */
    public EmailConfig createEmailConfig() {
        return new EmailConfig();
    }

    /**
     * Create an instance of {@link GolemConfig }
     *
     */
    public GolemConfig createGolemConfig() {
        return new GolemConfig();
    }

    /**
     * Create an instance of {@link PharusSubscriber }
     * 
     */
    public PharusSubscriber createPharusSubscriber() {
        return new PharusSubscriber();
    }

    /**
     * Create an instance of {@link PharusConfig }
     * 
     */
    public PharusConfig createPharusConfig() {
        return new PharusConfig();
    }

}
