//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 02:25:39 PM MSK 
//


package ru.yandex.qatools.camelot.core.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for TestEvent complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="TestEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:beans.qa.yandex.ru}config"/>
 *         &lt;element name="system" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="packagename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="methodname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *       &lt;attribute name="time" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestEvent", propOrder = {
        "config",
        "system",
        "profile",
        "packagename",
        "classname",
        "methodname",
        "timestamp"
})
@XmlSeeAlso({
        TestDropped.class,
        TestStarted.class,
        TestPassed.class,
        TestFailure.class
})
public abstract class TestEvent
        implements Serializable, TestEventData {

    @XmlElement(required = true)
    protected Config config;
    @XmlElement(required = true)
    protected String system;
    @XmlElement(required = true)
    protected String profile;
    @XmlElement(required = true)
    protected String packagename;
    @XmlElement(required = true)
    protected String classname;
    @XmlElement(required = true)
    protected String methodname;
    protected long timestamp;
    @XmlAttribute(name = "time", required = true)
    protected long time;

    /**
     * Gets the value of the config property.
     *
     * @return possible object is
     * {@link Config }
     */
    public Config getConfig() {
        return config;
    }

    /**
     * Sets the value of the config property.
     *
     * @param value allowed object is
     *              {@link Config }
     */
    public void setConfig(Config value) {
        this.config = value;
    }

    /**
     * Gets the value of the system property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSystem(String value) {
        this.system = value;
    }

    /**
     * Gets the value of the profile property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProfile(String value) {
        this.profile = value;
    }

    /**
     * Gets the value of the packagename property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPackagename() {
        return packagename;
    }

    /**
     * Sets the value of the packagename property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPackagename(String value) {
        this.packagename = value;
    }

    /**
     * Gets the value of the classname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClassname() {
        return classname;
    }

    /**
     * Sets the value of the classname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClassname(String value) {
        this.classname = value;
    }

    /**
     * Gets the value of the methodname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMethodname() {
        return methodname;
    }

    /**
     * Sets the value of the methodname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMethodname(String value) {
        this.methodname = value;
    }

    /**
     * Gets the value of the timestamp property.
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     */
    public void setTimestamp(long value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the time property.
     */
    public long getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     */
    public void setTime(long value) {
        this.time = value;
    }

}
